INSERT INTO coach_mast VALUES(5550,'Gianni De Biasi');
INSERT INTO coach_mast VALUES(5551,'Marcel Koller');
INSERT INTO coach_mast VALUES(5552,'Marc Wilmots');
INSERT INTO coach_mast VALUES(5553,'Ante Cacic');
INSERT INTO coach_mast VALUES(5554,'Pavel Vrba');
INSERT INTO coach_mast VALUES(5555,'Roy Hodgson');
INSERT INTO coach_mast VALUES(5556,'Didier Deschamps');
INSERT INTO coach_mast VALUES(5557,'Joachim Low');
INSERT INTO coach_mast VALUES(5558,'Bernd Storck');
INSERT INTO coach_mast VALUES(5559,'Lars Lagerback');
INSERT INTO coach_mast VALUES(5560,'Heimir Hallgrímsson');
INSERT INTO coach_mast VALUES(5561,'Antonio Conte');
INSERT INTO coach_mast VALUES(5562,'Michael ONeill');
INSERT INTO coach_mast VALUES(5563,'Adam Nawalka');
INSERT INTO coach_mast VALUES(5564,'Fernando Santos');
INSERT INTO coach_mast VALUES(5565,'Martin ONeill');
INSERT INTO coach_mast VALUES(5566,'Anghel Iordanescu');
INSERT INTO coach_mast VALUES(5567,'Leonid Slutski');
INSERT INTO coach_mast VALUES(5568,'Jan Kozak');
INSERT INTO coach_mast VALUES(5569,'Vicente del Bosque');
INSERT INTO coach_mast VALUES(5570,'Erik Hamren');
INSERT INTO coach_mast VALUES(5571,'Vladimir Petkovic');
INSERT INTO coach_mast VALUES(5572,'Fatih Terim');
INSERT INTO coach_mast VALUES(5573,'Mykhailo Fomenko');
INSERT INTO coach_mast VALUES(5574,'Chris Coleman');