INSERT INTO soccer_country VALUES(1201,'ALB','Albania');
INSERT INTO soccer_country VALUES(1202,'AUT','Austria');
INSERT INTO soccer_country VALUES(1203,'BEL','Belgium');
INSERT INTO soccer_country VALUES(1204,'CRO','Croatia');
INSERT INTO soccer_country VALUES(1205,'CZE','Czech Republic');
INSERT INTO soccer_country VALUES(1206,'ENG','England');
INSERT INTO soccer_country VALUES(1207,'FRA','France');
INSERT INTO soccer_country VALUES(1208,'GER','Germany');
INSERT INTO soccer_country VALUES(1209,'HUN','Hungary');
INSERT INTO soccer_country VALUES(1210,'ISL','Iceland');
INSERT INTO soccer_country VALUES(1211,'ITA','Italy');
INSERT INTO soccer_country VALUES(1212,'NIR','Northern Ireland');
INSERT INTO soccer_country VALUES(1213,'POL','Poland');
INSERT INTO soccer_country VALUES(1214,'POR','Portugal');
INSERT INTO soccer_country VALUES(1215,'IRL','Republic of Ireland');
INSERT INTO soccer_country VALUES(1216,'ROU','Romania');
INSERT INTO soccer_country VALUES(1217,'RUS','Russia');
INSERT INTO soccer_country VALUES(1218,'SVK','Slovakia');
INSERT INTO soccer_country VALUES(1219,'ESP','Spain');
INSERT INTO soccer_country VALUES(1220,'SWE','Sweden');
INSERT INTO soccer_country VALUES(1221,'SUI','Switzerland');
INSERT INTO soccer_country VALUES(1222,'TUR','Turkey');
INSERT INTO soccer_country VALUES(1223,'UKR','Ukraine');
INSERT INTO soccer_country VALUES(1224,'WAL','Wales');
INSERT INTO soccer_country VALUES(1225,'SLO','Slovenia');
INSERT INTO soccer_country VALUES(1226,'NED','Netherlands');
INSERT INTO soccer_country VALUES(1227,'SRB','Serbia');
INSERT INTO soccer_country VALUES(1228,'SCO','Scotland');
INSERT INTO soccer_country VALUES(1229,'NOR','Norway');